name: Flatpak Release

on:
  pull_request:
    paths:
      - '.github/workflows/flatpakci.yml'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    name: Build Tauri
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 3072
          root-reserve-mb: 6144
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-docker-images: 'true'
          
      - name: Clone Spacedrive to Working DIR
        run: |
          git clone https://github.com/spacedriveapp/spacedrive spacedrive
          mv spacedrive/* ./
          mv spacedrive/.github ./
          mv spacedrive/.[!.]* ./
          rm -rf spacedrive
          ls ./

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Setup System and Rust
        uses: ./.github/actions/setup-system
        with:
          target: x86_64-unknown-linux-gnu
          
      - name: Build Tauri
        run:  |
          pnpm tauri build --ci -v --target x86_64-unknown-linux-gnu --bundles deb

      - name: Upload Tauri Build
        uses: ./.github/actions/publish-artifacts
        with:
          os: linux
          arch: x86_64
          target: x86_64-unknown-linux-gnu
          profile: release
          
  flatpak-build:
    runs-on: ubuntu-22.04
    name: Flatpak Build
    needs: build
    permissions:
      contents: write
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: new-pr

      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: Add Submodules
        run: git submodule add https://github.com/flathub/shared-modules.git
        
      - name: Install FlatPak dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 librsvg2-dev patchelf flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y runtime/org.gnome.Platform/x86_64/46 runtime/org.gnome.Sdk/x86_64/46
          flatpak --version
          flatpak-builder --version
          ls
          
      - name: Build Flatpak
        run: flatpak-builder --repo=local ./out ./com.spacedrive.Desktop.yml
            
      - name: Build Flatpak Bundle
        run: flatpak build-bundle local com.spacedrive.Desktop.flatpak com.spacedrive.Desktop

      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v3
        with:
          name: com.spacedrive.Desktop.flatpak
          path: ./com.spacedrive.Desktop.flatpak
