name: Flatpak Release

on:
  pull_request:
    paths:
      - '.github/workflows/flatpakci.yml'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    name: Build Tauri
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 3072
          root-reserve-mb: 6144
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-docker-images: 'true'
          
      - name: Clone Spacedrive to Working DIR
        run: |
          git clone https://github.com/spacedriveapp/spacedrive spacedrive
          mv spacedrive/* ./
          mv spacedrive/.github ./
          mv spacedrive/.[!.]* ./
          rm -rf spacedrive
          ls ./

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Setup System and Rust
        uses: ./.github/actions/setup-system
        with:
          target: x86_64-unknown-linux-gnu

      - name: Get cargo pkgid output
        id: cargo-pkgid
        run: echo "::set-output name=pkgid::$(cargo pkgid --manifest-path ./core/Cargo.toml)"

      - name: Extract version
        id: extract-version
        run: |
          PKGID="${{ steps.cargo-pkgid.outputs.pkgid }}"
          VERSION=$(echo $PKGID | grep -oP '(?<=@)[^#]+$')
          echo "::set-output name=version::$VERSION"

      - name: Use version
        run: echo "The version is ${{ steps.extract-version.outputs.version }}"
          
      - name: Build Tauri
        run:  |
          pnpm tauri build --ci -v --target x86_64-unknown-linux-gnu --bundles deb

      - name: Publish Artifacts
        uses: ./.github/actions/publish-artifacts
        with:
          os: linux
          arch: x86_64
          target: x86_64-unknown-linux-gnu
          profile: release
      
      - name: Upload Tauri Build
        uses: actions/upload-artifact@v3
        with:
          name: build.deb
          path: ./target/x86_64-unknown-linux-gnu/release/bundle/deb/Spacedrive_${{ steps.extract-version.outputs.version }}_amd64.deb
          
  flatpak-build:
    runs-on: ubuntu-22.04
    name: Flatpak Build
    needs: build
    permissions:
      contents: write
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: new-pr

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build.deb
      
      - name: Add Submodules
        run: git submodule add https://github.com/flathub/shared-modules.git
        
      - name: Install FlatPak dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 librsvg2-dev patchelf flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y runtime/org.gnome.Platform/x86_64/46 runtime/org.gnome.Sdk/x86_64/46
          flatpak --version
          flatpak-builder --version
          ls
        
      - name: Create Flatpak Manifest
        run: |
          cat << EOF > ./com.spacedrive.Desktop.yml
          id: com.spacedrive.Desktop
          runtime: org.gnome.Platform
          runtime-version: '46'
          sdk: org.gnome.Sdk
          
          command: /app/bin/spacedrive
          finish-args:
            - --env=LD_LIBRARY_PATH=/app/lib/spacedrive:/usr/lib
            - --socket=wayland
            - --socket=fallback-x11
            - --device=dri
            - --allow=bluetooth
            - --share=ipc
            - --share=network
            - --socket=pulseaudio
            - --socket=cups
            - --device=dri
            - --filesystem=host
            - --filesystem=/mnt
          
          modules:
            - name: xdotool
              buildsystem: simple
              sources:
                - type: git
                  url: https://github.com/jordansissel/xdotool.git
              depends: glibc
              build-commands:
                - make
                - make install PREFIX=/app/lib/spacedrive
          
            - shared-modules/dbus-glib/dbus-glib.json
            - name: binary
              buildsystem: simple
              sources:
                - type: file
                  path: ./Spacedrive-linux-x86_64.deb 
                  only-arches: [x86_64]
          
              build-commands:
                - ar -x *.deb
                - tar -xf data.tar.xz
                - sed -i 's/Icon=sd-desktop/Icon=com.spacedrive.Desktop/' usr/share/applications/spacedrive.desktop
                - mkdir -p /app/bin
                - mkdir -p /app/lib/spacedrive
                - mkdir -p /app/share/applications
                - mkdir -p /app/share/doc/spacedrive
                - mkdir -p /app/share/icons/hicolor/32x32/apps
                - mkdir -p /app/share/icons/hicolor/128x128/apps
                - mkdir -p /app/share/icons/hicolor/256x256/apps
                - mkdir -p /app/share/man/man1/
                - mkdir -p /app/share/spacedrive/models
                - cp /app/lib/spacedrive/lib/*.so* /app/lib/spacedrive
                - cp /app/lib/*.so* /app/lib/spacedrive
                - install -Dm644 usr/lib/spacedrive/* /app/lib/spacedrive
                - install -Dm755 usr/bin/* /app/bin
                - install -Dm644 usr/share/man/man1/* /app/share/man/man1/
                - install -Dm644 usr/share/icons/hicolor/128x128/apps/spacedrive.png /app/share/icons/hicolor/128x128/apps/com.spacedrive.Desktop.png
                - install -Dm644 usr/share/icons/hicolor/32x32/apps/spacedrive.png /app/share/icons/hicolor/32x32/apps/com.spacedrive.Desktop.png
                - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/spacedrive.png /app/share/icons/hicolor/256x256/apps/com.spacedrive.Desktop.png
                - install -Dm644 usr/share/doc/spacedrive/* /app/share/doc/spacedrive
                - install -Dm644 usr/share/applications/spacedrive.desktop /app/share/applications/com.spacedrive.Desktop.desktop
                - install -Dm644 usr/share/spacedrive/models/* /app/share/spacedrive/models
                - install -Dm644 usr/com.spacedrive.Desktop.metainfo.xml /app/share/metainfo/com.spacedrive.Desktop.metainfo.xml
          EOF
          
      - name: Build Flatpak
        run: flatpak-builder --repo=local -v ./out ./com.spacedrive.Desktop.yml
            
      - name: Build Flatpak Bundle
        run: flatpak build-bundle local com.spacedrive.Desktop.flatpak com.spacedrive.Desktop

      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v3
        with:
          name: com.spacedrive.Desktop.flatpak
          path: ./com.spacedrive.Desktop.flatpak
