name: Flatpak Release

on:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:    
  flatpak-build:
    runs-on: ubuntu-22.04
    name: Flatpak Build
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: new-pr
      
      - name: Add Submodules
        run: git submodule add https://github.com/flathub/shared-modules.git
        
      - name: Install FlatPak dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y libc6 libxdo3 dbus libwebkit2gtk-4.1-0 gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad libgtk-3-0 librsvg2-dev patchelf flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y runtime/org.gnome.Platform/x86_64/46 runtime/org.gnome.Sdk/x86_64/46
          ls
          
      - name: Build Flatpak
        run: flatpak-builder --repo=local ./out ./com.spacedrive.Desktop.yml
            
      - name: Build Flatpak Bundle
        run: flatpak build-bundle local com.spacedrive.Desktop.flatpak com.spacedrive.Desktop

      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v3
        with:
          name: com.spacedrive.Desktop.flatpak
          path: ./com.spacedrive.Desktop.flatpak
